// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CT01ValidaEnvioMensagemTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void cT01ValidaEnvioMensagem() {
    driver.Navigate().GoToUrl("https://livros.inoveteste.com.br/");
    driver.Manage().Window.Size = new System.Drawing.Size(872, 1001);
    try {
      Thread.Sleep(//Pausa para carregar o site);
    } catch (Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    driver.FindElement(By.CssSelector("#sidr-navigation-container > #nav-wrap > #primary_menu > #menu-item-80 span")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".wpb_column:nth-child(1) h1")).Text, Is.EqualTo("Envie uma mensagem"));
    var elements = driver.FindElements(By.Name("your-name"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.Name("your-name")).SendKeys("Testes");
    var elements = driver.FindElements(By.Name("your-email"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.Name("your-email")).SendKeys("joice.jdosreis@gmail.com");
    var elements = driver.FindElements(By.Name("your-subject"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.Name("your-subject")).SendKeys("Curso Teste Automaçao");
    var elements = driver.FindElements(By.Name("your-message"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.Name("your-message")).SendKeys("teste");
    driver.FindElement(By.CssSelector(".wpcf7-submit")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".wpcf7-response-output")).Text, Is.EqualTo("Agradecemos a sua mensagem. Responderemos em breve."));
    driver.Close();
  }
}
