// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CT02ValidaCamposObrigatoriosTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void cT02ValidaCamposObrigatorios() {
    driver.Navigate().GoToUrl("https://livros.inoveteste.com.br/");
    driver.Manage().Window.Size = new System.Drawing.Size(872, 1000);
    driver.FindElement(By.CssSelector("#sidr-navigation-container > #nav-wrap > #primary_menu > #menu-item-80 span")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".wpb_column:nth-child(1) h1")).Text, Is.EqualTo("Envie uma mensagem"));
    var elements = driver.FindElements(By.Name("your-name"));
    Assert.True(elements.Count > 0);
    var elements = driver.FindElements(By.Name("your-email"));
    Assert.True(elements.Count > 0);
    var elements = driver.FindElements(By.Name("your-subject"));
    Assert.True(elements.Count > 0);
    var elements = driver.FindElements(By.Name("your-message"));
    Assert.True(elements.Count > 0);
    var elements = driver.FindElements(By.CssSelector(".wpcf7-submit"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector(".wpcf7-submit")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".your-name > .wpcf7-not-valid-tip")).Text, Is.EqualTo("O campo é obrigatório."));
    Assert.That(driver.FindElement(By.CssSelector(".your-email > .wpcf7-not-valid-tip")).Text, Is.EqualTo("O campo é obrigatório."));
    Assert.That(driver.FindElement(By.CssSelector(".your-subject > .wpcf7-not-valid-tip")).Text, Is.EqualTo("O campo é obrigatório."));
    Assert.That(driver.FindElement(By.CssSelector(".your-message > .wpcf7-not-valid-tip")).Text, Is.EqualTo("O campo é obrigatório."));
    Assert.That(driver.FindElement(By.CssSelector(".wpcf7-response-output")).Text, Is.EqualTo("Um ou mais campos possuem um erro. Verifique e tente novamente."));
    driver.Close();
  }
}
