// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT01-ValidaEnvioMensagem', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT01-ValidaEnvioMensagem', async function() {
    await driver.get("https://livros.inoveteste.com.br/")
    await driver.manage().window().setRect({ width: 872, height: 1001 })
    await driver.sleep(//Pausa para carregar o site)
    await driver.findElement(By.css("#sidr-navigation-container > #nav-wrap > #primary_menu > #menu-item-80 span")).click()
    assert(await driver.findElement(By.css(".wpb_column:nth-child(1) h1")).getText() == "Envie uma mensagem")
    {
      const elements = await driver.findElements(By.name("your-name"))
      assert(elements.length)
    }
    await driver.findElement(By.name("your-name")).sendKeys("Testes")
    {
      const elements = await driver.findElements(By.name("your-email"))
      assert(elements.length)
    }
    await driver.findElement(By.name("your-email")).sendKeys("joice.jdosreis@gmail.com")
    {
      const elements = await driver.findElements(By.name("your-subject"))
      assert(elements.length)
    }
    await driver.findElement(By.name("your-subject")).sendKeys("Curso Teste Automaçao")
    {
      const elements = await driver.findElements(By.name("your-message"))
      assert(elements.length)
    }
    await driver.findElement(By.name("your-message")).sendKeys("teste")
    await driver.findElement(By.css(".wpcf7-submit")).click()
    assert(await driver.findElement(By.css(".wpcf7-response-output")).getText() == "Agradecemos a sua mensagem. Responderemos em breve.")
    await driver.close()
  })
})
