// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT02-ValidaCamposObrigatorios', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT02-ValidaCamposObrigatorios', async function() {
    await driver.get("https://livros.inoveteste.com.br/")
    await driver.manage().window().setRect({ width: 872, height: 1000 })
    await driver.findElement(By.css("#sidr-navigation-container > #nav-wrap > #primary_menu > #menu-item-80 span")).click()
    assert(await driver.findElement(By.css(".wpb_column:nth-child(1) h1")).getText() == "Envie uma mensagem")
    {
      const elements = await driver.findElements(By.name("your-name"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.name("your-email"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.name("your-subject"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.name("your-message"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.css(".wpcf7-submit"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".wpcf7-submit")).click()
    assert(await driver.findElement(By.css(".your-name > .wpcf7-not-valid-tip")).getText() == "O campo é obrigatório.")
    assert(await driver.findElement(By.css(".your-email > .wpcf7-not-valid-tip")).getText() == "O campo é obrigatório.")
    assert(await driver.findElement(By.css(".your-subject > .wpcf7-not-valid-tip")).getText() == "O campo é obrigatório.")
    assert(await driver.findElement(By.css(".your-message > .wpcf7-not-valid-tip")).getText() == "O campo é obrigatório.")
    assert(await driver.findElement(By.css(".wpcf7-response-output")).getText() == "Um ou mais campos possuem um erro. Verifique e tente novamente.")
    await driver.close()
  })
})
